<?php

if (!defined('KIRPI_CORE_ENTRY')) {
    exit;
}

function settings_lang(string $key, ?string $default = null): string
{
    static $dictionary = null;

    if ($dictionary === null) {
        $dictionary = [
            'tr' => [
                'system_management' => 'Sistem Yonetimi',
                'settings' => 'Ayarlar',
                'session_data' => 'Session Verileri',
                'settings_table_missing' => 'Ayarlar tablosu kurulu degil. Kurulum icin setup veya db:install calistirin.',
                'system_check' => 'Sistem Kontrol ve Eksik Kurulum',
                'required_total_tables' => 'Beklenen Toplam Tablo',
                'missing_table' => 'Eksik Tablo',
                'missing_index_expected' => 'Eksik Indeks / Beklenen',
                'missing_column_expected' => 'Eksik Kolon / Beklenen',
                'install_missing' => 'Eksikleri Kur',
                'missing_schema_files' => 'Eksik tablo bulunan schema dosyalari:',
                'missing_indexes' => 'Eksik indeksler:',
                'missing_columns' => 'Eksik kolonlar:',
                'application' => 'Uygulama',
                'application_name' => 'Uygulama Adi',
                'api_status' => 'API Durumu',
                'rest_api_active' => 'REST API aktif',
                'api_disabled_hint' => 'Kapali oldugunda /api/v1/* endpointleri 503 doner.',
                'mail' => 'Mail',
                'mail_password_placeholder' => 'Degistirmek icin yeni sifre girin',
                'password_defined' => 'Parola tanimli (guvenlik icin gosterilmiyor).',
                'password_missing' => 'Parola tanimli degil.',
                'save_settings' => 'Ayarlari Kaydet',
                'module_management' => 'Modul Yonetimi',
                'app_modules_missing' => 'app_modules tablosu hazir degil. Ayarlar ekranindan Eksikleri Kur calistirin.',
                'modules' => 'Moduller',
                'name' => 'Ad',
                'version' => 'Versiyon',
                'order' => 'Sira',
                'dependency' => 'Bagimlilik',
                'dependent_modules' => 'Kullanan Moduller',
                'type' => 'Tip',
                'status' => 'Durum',
                'operation' => 'Islem',
                'module_not_found' => 'Modul bulunamadi.',
                'core' => 'Core',
                'plugin' => 'Plugin',
                'active' => 'Aktif',
                'passive' => 'Pasif',
                'locked' => 'Kilitle',
                'disable_confirm' => 'Bu modul devre disi birakilacak. Emin misiniz?',
                'enable_confirm' => 'Bu modul aktif edilecek. Emin misiniz?',
                'disable_blocked_title_prefix' => 'Disable engelli. Aktif bagimli moduller: ',
                'dependent_module_exists' => 'Bagimli Modul Var',
                'disable' => 'Disable',
                'enable' => 'Enable',
                'api_test_center' => 'API Test Merkezi',
                'method' => 'Method',
                'endpoint' => 'Endpoint',
                'bearer_token' => 'Bearer Token',
                'json_body' => 'JSON Body (POST/PATCH/DELETE)',
                'send_request' => 'Istek Gonder',
                'result' => 'Sonuc',
                'ready' => 'Hazir',
                'request_not_sent' => 'Henuz istek gonderilmedi.',
                'endpoint_empty_warning' => 'Endpoint bos olamaz.',
                'sending' => 'Istek gonderiliyor...',
                'pending' => 'Bekleniyor',
                'error' => 'Hata',
                'invalid_json_prefix' => 'JSON Body gecersiz: ',
                'session_modal_title' => 'Session Verileri',
                'session_mask_info' => 'Hassas alanlar otomatik olarak maskelenir.',
                'close' => 'Kapat',
                'csrf_failed' => 'Guvenlik dogrulamasi basarisiz oldu.',
                'settings_table_not_ready' => 'Ayarlar tablosu henuz kurulu degil.',
                'app_name_required' => 'Uygulama adi bos olamaz.',
                'mail_port_invalid' => 'MAIL_PORT sayisal ve pozitif olmalidir.',
                'mail_encryption_invalid' => 'MAIL_ENCRYPTION gecersiz.',
                'mail_from_invalid' => 'MAIL_FROM_ADDRESS gecersiz bir e-posta adresi.',
                'settings_updated' => 'Ayarlar basariyla guncellendi.',
                'settings_update_error' => 'Ayarlar guncellenirken bir hata olustu.',
                'module_key_required' => 'Modul anahtari zorunludur.',
                'module_update_failed' => 'Modul durumu guncellenemedi.',
                'module_updated' => 'Modul durumu guncellendi.',
                'module_update_error' => 'Modul durumu guncellenirken bir hata olustu.',
                'no_missing_schema' => 'Eksik tablo, kolon veya indeks yok. Sistem zaten tam.',
                'missing_installed' => 'Eksik tablo, kolon ve indeksler basariyla kuruldu.',
                'still_missing' => 'Kurulum denendi ancak halen eksikler var. Loglari kontrol edin.',
                'install_missing_error' => 'Eksik tablolar kurulurken bir hata olustu.',
            ],
            'en' => [
                'system_management' => 'System Management',
                'settings' => 'Settings',
                'session_data' => 'Session Data',
                'settings_table_missing' => 'Settings table is not installed. Run setup or db:install.',
                'system_check' => 'System Check and Missing Install',
                'required_total_tables' => 'Required Total Tables',
                'missing_table' => 'Missing Table',
                'missing_index_expected' => 'Missing Index / Required',
                'missing_column_expected' => 'Missing Column / Required',
                'install_missing' => 'Install Missing',
                'missing_schema_files' => 'Schema files with missing tables:',
                'missing_indexes' => 'Missing indexes:',
                'missing_columns' => 'Missing columns:',
                'application' => 'Application',
                'application_name' => 'Application Name',
                'api_status' => 'API Status',
                'rest_api_active' => 'REST API active',
                'api_disabled_hint' => 'When disabled, /api/v1/* endpoints return 503.',
                'mail' => 'Mail',
                'mail_password_placeholder' => 'Enter new password to change',
                'password_defined' => 'Password is set (hidden for security).',
                'password_missing' => 'Password is not set.',
                'save_settings' => 'Save Settings',
                'module_management' => 'Module Management',
                'app_modules_missing' => 'app_modules table is not ready. Run Install Missing from settings page.',
                'modules' => 'Modules',
                'name' => 'Name',
                'version' => 'Version',
                'order' => 'Order',
                'dependency' => 'Dependency',
                'dependent_modules' => 'Dependent Modules',
                'type' => 'Type',
                'status' => 'Status',
                'operation' => 'Operation',
                'module_not_found' => 'No module found.',
                'core' => 'Core',
                'plugin' => 'Plugin',
                'active' => 'Active',
                'passive' => 'Passive',
                'locked' => 'Locked',
                'disable_confirm' => 'This module will be disabled. Continue?',
                'enable_confirm' => 'This module will be enabled. Continue?',
                'disable_blocked_title_prefix' => 'Disable blocked. Active dependent modules: ',
                'dependent_module_exists' => 'Has Dependents',
                'disable' => 'Disable',
                'enable' => 'Enable',
                'api_test_center' => 'API Test Center',
                'method' => 'Method',
                'endpoint' => 'Endpoint',
                'bearer_token' => 'Bearer Token',
                'json_body' => 'JSON Body (POST/PATCH/DELETE)',
                'send_request' => 'Send Request',
                'result' => 'Result',
                'ready' => 'Ready',
                'request_not_sent' => 'No request sent yet.',
                'endpoint_empty_warning' => 'Endpoint cannot be empty.',
                'sending' => 'Sending request...',
                'pending' => 'Pending',
                'error' => 'Error',
                'invalid_json_prefix' => 'Invalid JSON Body: ',
                'session_modal_title' => 'Session Data',
                'session_mask_info' => 'Sensitive fields are masked automatically.',
                'close' => 'Close',
                'csrf_failed' => 'Security validation failed.',
                'settings_table_not_ready' => 'Settings table is not installed yet.',
                'app_name_required' => 'Application name cannot be empty.',
                'mail_port_invalid' => 'MAIL_PORT must be numeric and positive.',
                'mail_encryption_invalid' => 'MAIL_ENCRYPTION is invalid.',
                'mail_from_invalid' => 'MAIL_FROM_ADDRESS is not a valid email address.',
                'settings_updated' => 'Settings updated successfully.',
                'settings_update_error' => 'An error occurred while updating settings.',
                'module_key_required' => 'Module key is required.',
                'module_update_failed' => 'Module status could not be updated.',
                'module_updated' => 'Module status updated.',
                'module_update_error' => 'An error occurred while updating module status.',
                'no_missing_schema' => 'No missing tables, columns, or indexes. System is complete.',
                'missing_installed' => 'Missing tables, columns, and indexes installed successfully.',
                'still_missing' => 'Installation attempted but some items are still missing. Check logs.',
                'install_missing_error' => 'An error occurred while installing missing schema.',
            ],
        ];
    }

    $locale = strtolower((string) env('APP_LOCALE', 'tr'));
    if (!isset($dictionary[$locale])) {
        $locale = 'tr';
    }

    if (isset($dictionary[$locale][$key])) {
        return $dictionary[$locale][$key];
    }

    if (isset($dictionary['tr'][$key])) {
        return $dictionary['tr'][$key];
    }

    return $default ?? $key;
}
