<?php

if (!defined('KIRPI_CORE_ENTRY')) {
    exit;
}

function profile_lang(string $key, ?string $default = null): string
{
    static $dictionary = null;

    if ($dictionary === null) {
        $dictionary = [
            'tr' => [
                'forbidden_title' => '403 - Yetkisiz Erisim',
                'forbidden_message' => 'Profil bilgilerine erisilemedi.',
                'load_error_title' => '500 - Profil Yuklenemedi',
                'load_error_message' => 'Profil verileri yuklenirken bir hata olustu.',
                'no_role' => 'Rol Yok',
                'active' => 'Aktif',
                'passive' => 'Pasif',
                'my_account' => 'Hesabim',
                'profile' => 'Profil',
                'profile_info' => 'Profil Bilgileri',
                'api_tokens' => 'API Tokenleri',
                'name_surname' => 'Ad Soyad',
                'email' => 'E-posta',
                'new_password' => 'Yeni Sifre',
                'new_password_repeat' => 'Yeni Sifre Tekrar',
                'password_placeholder' => 'Bos birakilirsa degismez',
                'password_hint' => 'Sifre degistirmek istemiyorsaniz bos birakin.',
                'avatar' => 'Profil Gorseli',
                'avatar_hint' => 'JPG, PNG veya WEBP. Maksimum 2 MB.',
                'update_profile' => 'Profili Guncelle',
                'api_token_management' => 'API Token Yonetimi (Super Admin)',
                'token_once_warning' => 'Bu token sadece bir kez gosterilir. Guvenli bir yerde saklayin.',
                'token' => 'Token',
                'copy' => 'Kopyala',
                'copy_title' => 'Kopyala',
                'token_name' => 'Token Name',
                'expires_at' => 'Expires At',
                'unlimited' => 'Sinirsiz',
                'scopes' => 'Scopes',
                'validity' => 'Gecerlilik',
                'scope' => 'Scope',
                'all_permissions' => 'Tum Yetki (*)',
                'profile_only' => 'Sadece Profil',
                'users_read' => 'Users Read',
                'users_manage' => 'Users Manage',
                'create_api_token' => 'API Token Olustur',
                'api_disabled_warning' => 'API su an Ayarlar ekranindan kapatildi.',
                'api_table_warning' => '`api_tokens` tablosu hazir degil. Ayarlar > Eksikleri Kur calistirin.',
                'no_tokens' => 'API token kaydi yok.',
                'created' => 'Created',
                'last_used' => 'Last Used',
                'expires' => 'Expires',
                'status' => 'Status',
                'revoked' => 'Revoked',
                'expired' => 'Expired',
                'active_en' => 'Active',
                'copy_disabled_title' => 'Guvenlik nedeniyle sadece bu oturumda olusturulan tokenlar kopyalanabilir',
                'revoke_confirm' => 'Bu API token iptal edilecek. Emin misiniz?',
                'revoke' => 'Revoke',
                'lock_key_title' => 'Oturum Kilitleme Key',
                'lock_enabled' => 'Oturum kilitleme aktif',
                'lock_hint' => "Navbar'daki user-key ikonu ile ekrani kilitleyebilirsiniz.",
                'new_key' => 'Yeni Key (4 hane)',
                'key_repeat' => 'Key Tekrar',
                'key_placeholder' => 'Ornek: 1234',
                'save_key' => 'Key Ayarini Kaydet',
                'copy_not_allowed' => 'Bu token bu oturumda kopyalanamaz.',
                'copy_success' => 'Token panoya kopyalandi.',
                'copy_error' => 'Token kopyalanamadi.',
                'csrf_failed' => 'Guvenlik dogrulamasi basarisiz oldu.',
                'invalid_session' => 'Gecersiz kullanici oturumu.',
                'required_fields' => 'Ad soyad ve e-posta alanlari zorunludur.',
                'invalid_email' => 'Gecerli bir e-posta adresi girin.',
                'password_min' => 'Yeni sifre en az 6 karakter olmalidir.',
                'password_mismatch' => 'Yeni sifreler uyusmuyor.',
                'user_not_found' => 'Kullanici bulunamadi.',
                'email_in_use' => 'Bu e-posta adresi baska bir kullanici tarafindan kullaniliyor.',
                'profile_updated' => 'Profil basariyla guncellendi.',
                'profile_update_error' => 'Profil guncellenirken bir hata olustu.',
                'valid_session_required' => 'Gecerli kullanici oturumu bulunamadi.',
                'lock_infra_missing' => 'Oturum kilitleme altyapisi hazir degil. Ayarlar > Eksikleri Kur calistirin.',
                'key_format_error' => 'Key sadece rakam olmali ve 4 hane olmalidir.',
                'key_repeat_error' => 'Key tekrar alani uyusmuyor.',
                'key_required_for_enable' => 'Oturum kilitlemeyi acmak icin once bir key tanimlamalisiniz.',
                'lock_settings_updated' => 'Oturum kilitleme ayarlari guncellendi.',
                'settings_update_error' => 'Ayarlar guncellenirken bir hata olustu.',
                'super_admin_only_create' => 'Sadece Super Admin API token olusturabilir.',
                'api_disabled_token' => 'API devre disi oldugu icin token olusturulamadi.',
                'api_table_not_ready' => 'API token tablosu hazir degil. Once Eksikleri Kur calistirin.',
                'token_create_failed' => 'API token olusturulamadi.',
                'token_created_once' => 'API token olusturuldu. Profil sayfasinda bir kez gosterilecek.',
                'token_create_error' => 'API token olusturulurken bir hata olustu.',
                'super_admin_only_manage' => 'Sadece Super Admin API token yonetebilir.',
                'invalid_token_record' => 'Gecersiz token kaydi.',
                'token_table_not_ready' => 'API token tablosu hazir degil.',
                'token_not_found_or_revoked' => 'Token bulunamadi veya zaten iptal edilmis.',
                'token_revoked' => 'API token iptal edildi.',
                'token_revoke_error' => 'Token iptal edilirken bir hata olustu.',
            ],
            'en' => [
                'forbidden_title' => '403 - Unauthorized Access',
                'forbidden_message' => 'Profile information could not be accessed.',
                'load_error_title' => '500 - Profile Load Failed',
                'load_error_message' => 'An error occurred while loading profile data.',
                'no_role' => 'No Role',
                'active' => 'Active',
                'passive' => 'Passive',
                'my_account' => 'My Account',
                'profile' => 'Profile',
                'profile_info' => 'Profile Information',
                'api_tokens' => 'API Tokens',
                'name_surname' => 'Full Name',
                'email' => 'Email',
                'new_password' => 'New Password',
                'new_password_repeat' => 'Repeat New Password',
                'password_placeholder' => 'Leave blank to keep unchanged',
                'password_hint' => 'Leave blank if you do not want to change password.',
                'avatar' => 'Profile Image',
                'avatar_hint' => 'JPG, PNG or WEBP. Maximum 2 MB.',
                'update_profile' => 'Update Profile',
                'api_token_management' => 'API Token Management (Super Admin)',
                'token_once_warning' => 'This token is shown only once. Store it securely.',
                'token' => 'Token',
                'copy' => 'Copy',
                'copy_title' => 'Copy',
                'token_name' => 'Token Name',
                'expires_at' => 'Expires At',
                'unlimited' => 'Unlimited',
                'scopes' => 'Scopes',
                'validity' => 'Validity',
                'scope' => 'Scope',
                'all_permissions' => 'Full Access (*)',
                'profile_only' => 'Profile Only',
                'users_read' => 'Users Read',
                'users_manage' => 'Users Manage',
                'create_api_token' => 'Create API Token',
                'api_disabled_warning' => 'API is currently disabled from Settings.',
                'api_table_warning' => '`api_tokens` table is not ready. Run Settings > Install Missing.',
                'no_tokens' => 'No API tokens found.',
                'created' => 'Created',
                'last_used' => 'Last Used',
                'expires' => 'Expires',
                'status' => 'Status',
                'revoked' => 'Revoked',
                'expired' => 'Expired',
                'active_en' => 'Active',
                'copy_disabled_title' => 'For security, only tokens created in this session can be copied',
                'revoke_confirm' => 'This API token will be revoked. Continue?',
                'revoke' => 'Revoke',
                'lock_key_title' => 'Session Lock Key',
                'lock_enabled' => 'Session lock enabled',
                'lock_hint' => 'You can lock the screen with the user-key icon in navbar.',
                'new_key' => 'New Key (4 digits)',
                'key_repeat' => 'Repeat Key',
                'key_placeholder' => 'Example: 1234',
                'save_key' => 'Save Key Settings',
                'copy_not_allowed' => 'This token cannot be copied in this session.',
                'copy_success' => 'Token copied to clipboard.',
                'copy_error' => 'Token could not be copied.',
                'csrf_failed' => 'Security validation failed.',
                'invalid_session' => 'Invalid user session.',
                'required_fields' => 'Full name and email are required.',
                'invalid_email' => 'Enter a valid email address.',
                'password_min' => 'New password must be at least 6 characters.',
                'password_mismatch' => 'New passwords do not match.',
                'user_not_found' => 'User not found.',
                'email_in_use' => 'This email is already used by another user.',
                'profile_updated' => 'Profile updated successfully.',
                'profile_update_error' => 'An error occurred while updating profile.',
                'valid_session_required' => 'Valid user session not found.',
                'lock_infra_missing' => 'Session lock infrastructure is not ready. Run Settings > Install Missing.',
                'key_format_error' => 'Key must be numeric and exactly 4 digits.',
                'key_repeat_error' => 'Key repeat does not match.',
                'key_required_for_enable' => 'You must define a key before enabling session lock.',
                'lock_settings_updated' => 'Session lock settings updated.',
                'settings_update_error' => 'An error occurred while updating settings.',
                'super_admin_only_create' => 'Only Super Admin can create API tokens.',
                'api_disabled_token' => 'API is disabled, token could not be created.',
                'api_table_not_ready' => 'API token table is not ready. Run Install Missing first.',
                'token_create_failed' => 'API token could not be created.',
                'token_created_once' => 'API token created. It will be shown once on profile page.',
                'token_create_error' => 'An error occurred while creating API token.',
                'super_admin_only_manage' => 'Only Super Admin can manage API tokens.',
                'invalid_token_record' => 'Invalid token record.',
                'token_table_not_ready' => 'API token table is not ready.',
                'token_not_found_or_revoked' => 'Token not found or already revoked.',
                'token_revoked' => 'API token revoked.',
                'token_revoke_error' => 'An error occurred while revoking token.',
            ],
        ];
    }

    $locale = strtolower((string) env('APP_LOCALE', 'tr'));
    if (!isset($dictionary[$locale])) {
        $locale = 'tr';
    }

    if (isset($dictionary[$locale][$key])) {
        return $dictionary[$locale][$key];
    }

    if (isset($dictionary['tr'][$key])) {
        return $dictionary['tr'][$key];
    }

    return $default ?? $key;
}
