<?php

if (!defined('KIRPI_CORE_ENTRY')) {
    exit;
}

function ai_lang(string $key, ?string $default = null): string
{
    static $dictionary = null;

    if ($dictionary === null) {
        $dictionary = [
            'tr' => [
                'system_management' => 'Sistem Yönetimi',
                'kirpi_intelligence' => 'Kirpi Intelligence',
                'subtitle' => 'Core AI altyapısı',
                'schema_registry' => 'Schema Registry',
                'schema_registry_detail' => 'Modül veri yapıları merkezi olarak burada yayınlanır.',
                'ai_audit_log' => 'AI Audit Log',
                'ai_audit_log_detail' => 'AI işlemleri hem genel audit hem de AI audit tablosuna yazılır.',
                'model_adapters' => 'Model Adapters',
                'model_adapters_detail' => 'Model seçimi ürünlerden ayrılır ve Core tarafından yönetilir.',
                'active_entities' => 'Aktif Entity',
                'active_fields' => 'Aktif Field',
                'metadata_index' => 'Metadata Index',
                'metadata_index_detail' => 'Schema aramaları için alias, açıklama ve field metadata girdileri indekslenir.',
                'index_records' => 'İndeks Kaydı',
                'audit_records' => 'Audit Kaydı',
                'adapter_count' => 'Adapter',
                'latest_entities' => 'Son Schema Entity Kayıtları',
                'module' => 'Modül',
                'entity' => 'Entity',
                'table' => 'Tablo',
                'fields' => 'Fields',
                'entities' => 'Entity',
                'permission' => 'Yetki',
                'updated_at' => 'Güncelleme',
                'no_schema' => 'Henüz schema entity kaydı yok.',
                'schema_missing' => 'AI schema tabloları henüz kurulmamış.',
                'adapter_missing' => 'Model adapter tablosu henüz kurulmamış.',
                'status_ready' => 'Hazır',
                'status_missing' => 'Eksik',
                'read_only_notice' => 'İlk sürüm metadata-only ve read-only çalışacak şekilde hazırlandı.',
                'schema_manifests' => 'Schema Manifest',
                'sync_schema' => 'Schema Sync',
                'csrf_failed' => 'Oturum doğrulaması başarısız. Sayfayı yenileyip tekrar deneyin.',
                'schema_sync_success' => 'Schema registry güncellendi: %d entity, %d field, %d index kaydı.',
                'schema_sync_partial' => 'Schema registry kısmen güncellendi. Logları kontrol edin.',
                'schema_sync_error' => 'Schema registry güncellenemedi.',
                'discovery_preview' => 'Discovery Önizleme',
                'discovery_preview_detail' => 'Bu liste mevcut kullanıcının yetkilerine göre filtrelenir. Hassas alanlar varsayılan olarak gizlenir.',
                'visible_entities' => 'Görünen Entity',
                'visible_fields' => 'Görünen Field',
                'sensitive_hidden' => 'Hassas alanlar gizli',
                'sensitive_visible' => 'Hassas alanlar görünür',
                'visible_field_list' => 'Görünen Alanlar',
                'no_discovery_schema' => 'Bu kullanıcı için keşfedilebilir schema bulunamadı.',
                'latest_schema_sync' => 'Son Schema Sync',
                'manifest_file' => 'Manifest Dosyası',
                'limit' => 'Limit',
                'filterable_only' => 'Sadece filtrelenebilir alanlar',
                'include_sensitive' => 'Hassas alanları göster',
                'clear_filters' => 'Temizle',
                'entity_description' => 'Entity Açıklaması',
                'field_name' => 'Field',
                'field_type' => 'Field Tipi',
                'field_description' => 'Field Açıklaması',
                'is_sensitive' => 'Hassas',
                'is_filterable' => 'Filtrelenebilir',
                'entity_metadata' => 'Entity Metadata',
                'field_metadata' => 'Field Metadata',
                'schema_quality' => 'Schema Kalite Kontrolü',
                'schema_quality_error' => 'Schema kalite raporu üretilemedi.',
                'quality_warnings' => 'Uyarı',
                'quality_errors' => 'Hata',
                'severity' => 'Seviye',
                'quality_code' => 'Kod',
                'quality_message' => 'Mesaj',
                'no_quality_warnings' => 'Schema kalite uyarısı bulunamadı.',
                'metadata_search' => 'Metadata Search',
                'metadata_search_detail' => 'Yetki kontrollü, hassas alanları dışarıda bırakan ilk arama katmanı.',
                'search_query' => 'Arama',
                'search_placeholder' => 'Örn: kullanıcı, role, aktif',
                'search' => 'Ara',
                'score' => 'Skor',
                'matched_fields' => 'Eşleşen Alanlar',
                'matched_terms' => 'Eşleşen Terimler',
                'match_reason' => 'Eşleşme Nedeni',
                'search_mode' => 'Arama Modu',
                'no_search_results' => 'Bu arama için sonuç bulunamadı.',
                'view_audit' => 'Audit Log',
                'back_to_ai' => 'AI Ekranına Dön',
                'audit_missing' => 'AI audit tablosu henüz kurulmamış.',
                'filters' => 'Filtreler',
                'all' => 'Tümü',
                'status' => 'Durum',
                'action' => 'İşlem',
                'model_adapter' => 'Model Adapter',
                'entity_type' => 'Entity Türü',
                'user_id' => 'Kullanıcı ID',
                'filter' => 'Filtrele',
                'records' => 'Kayıtlar',
                'total' => 'Toplam',
                'date' => 'Tarih',
                'user' => 'Kullanıcı',
                'route' => 'Rota',
                'detail' => 'Detay',
                'view' => 'Görüntüle',
                'previous' => 'Önceki',
                'next' => 'Sonraki',
                'no_audit_records' => 'AI audit kaydı bulunamadı.',
            ],
            'en' => [
                'system_management' => 'System Management',
                'kirpi_intelligence' => 'Kirpi Intelligence',
                'subtitle' => 'Core AI infrastructure',
                'schema_registry' => 'Schema Registry',
                'schema_registry_detail' => 'Module data structures are published centrally here.',
                'ai_audit_log' => 'AI Audit Log',
                'ai_audit_log_detail' => 'AI operations are written to both general audit and AI audit tables.',
                'model_adapters' => 'Model Adapters',
                'model_adapters_detail' => 'Model selection is decoupled from products and managed by Core.',
                'active_entities' => 'Active Entities',
                'active_fields' => 'Active Fields',
                'metadata_index' => 'Metadata Index',
                'metadata_index_detail' => 'Alias, description, and field metadata entries are indexed for schema search.',
                'index_records' => 'Index Records',
                'audit_records' => 'Audit Records',
                'adapter_count' => 'Adapters',
                'latest_entities' => 'Latest Schema Entities',
                'module' => 'Module',
                'entity' => 'Entity',
                'table' => 'Table',
                'fields' => 'Fields',
                'entities' => 'Entities',
                'permission' => 'Permission',
                'updated_at' => 'Updated At',
                'no_schema' => 'No schema entity has been registered yet.',
                'schema_missing' => 'AI schema tables are not installed yet.',
                'adapter_missing' => 'Model adapter table is not installed yet.',
                'status_ready' => 'Ready',
                'status_missing' => 'Missing',
                'read_only_notice' => 'The first version is prepared as metadata-only and read-only.',
                'schema_manifests' => 'Schema Manifests',
                'sync_schema' => 'Sync Schema',
                'csrf_failed' => 'Session validation failed. Refresh the page and try again.',
                'schema_sync_success' => 'Schema registry updated: %d entities, %d fields, %d index records.',
                'schema_sync_partial' => 'Schema registry was partially updated. Check logs.',
                'schema_sync_error' => 'Schema registry could not be updated.',
                'discovery_preview' => 'Discovery Preview',
                'discovery_preview_detail' => 'This list is filtered by the current user permissions. Sensitive fields are hidden by default.',
                'visible_entities' => 'Visible Entities',
                'visible_fields' => 'Visible Fields',
                'sensitive_hidden' => 'Sensitive fields hidden',
                'sensitive_visible' => 'Sensitive fields visible',
                'visible_field_list' => 'Visible Fields',
                'no_discovery_schema' => 'No discoverable schema is available for this user.',
                'latest_schema_sync' => 'Latest Schema Sync',
                'manifest_file' => 'Manifest File',
                'limit' => 'Limit',
                'filterable_only' => 'Filterable fields only',
                'include_sensitive' => 'Show sensitive fields',
                'clear_filters' => 'Clear',
                'entity_description' => 'Entity Description',
                'field_name' => 'Field',
                'field_type' => 'Field Type',
                'field_description' => 'Field Description',
                'is_sensitive' => 'Sensitive',
                'is_filterable' => 'Filterable',
                'entity_metadata' => 'Entity Metadata',
                'field_metadata' => 'Field Metadata',
                'schema_quality' => 'Schema Quality Check',
                'schema_quality_error' => 'Schema quality report could not be generated.',
                'quality_warnings' => 'Warnings',
                'quality_errors' => 'Errors',
                'severity' => 'Severity',
                'quality_code' => 'Code',
                'quality_message' => 'Message',
                'no_quality_warnings' => 'No schema quality warnings were found.',
                'metadata_search' => 'Metadata Search',
                'metadata_search_detail' => 'The first permission-aware search layer that excludes sensitive fields.',
                'search_query' => 'Search',
                'search_placeholder' => 'Ex: user, role, active',
                'search' => 'Search',
                'score' => 'Score',
                'matched_fields' => 'Matched Fields',
                'matched_terms' => 'Matched Terms',
                'match_reason' => 'Match Reason',
                'search_mode' => 'Search Mode',
                'no_search_results' => 'No results were found for this search.',
                'view_audit' => 'Audit Log',
                'back_to_ai' => 'Back to AI',
                'audit_missing' => 'AI audit table has not been installed yet.',
                'filters' => 'Filters',
                'all' => 'All',
                'status' => 'Status',
                'action' => 'Action',
                'model_adapter' => 'Model Adapter',
                'entity_type' => 'Entity Type',
                'user_id' => 'User ID',
                'filter' => 'Filter',
                'records' => 'Records',
                'total' => 'Total',
                'date' => 'Date',
                'user' => 'User',
                'route' => 'Route',
                'detail' => 'Detail',
                'view' => 'View',
                'previous' => 'Previous',
                'next' => 'Next',
                'no_audit_records' => 'No AI audit records were found.',
            ],
        ];
    }

    $locale = strtolower((string) env('APP_LOCALE', 'tr'));
    if (!isset($dictionary[$locale])) {
        $locale = 'tr';
    }

    if (isset($dictionary[$locale][$key])) {
        return $dictionary[$locale][$key];
    }

    if (isset($dictionary['tr'][$key])) {
        return $dictionary['tr'][$key];
    }

    return $default ?? $key;
}
